services:
  primary-db:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=primary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      interval: 3s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 5s
    ports:
      - 5432:5432
    profiles:
      - infra
    restart: on-failure

  redis:
    image: redis:7.2.4
    healthcheck:
      interval: 3s
      retries: 5
      test: ["CMD-SHELL", "redis-cli ping"]
      timeout: 5s
    ports:
      - 6379:6379
    profiles:
      - infra
    restart: on-failure

  smtp:
    image: axllent/mailpit:v1.18.6
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - 8025:8025
      - 1025:1025
    profiles:
      - infra
    restart: on-failure

  storage:
    image: minio/minio:RELEASE.2024-03-07T00-43-48Z
    command: minio server /data --console-address "0.0.0.0:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=whatever
    healthcheck:
      interval: 3s
      test: timeout 5s bash -c ':> /dev/tcp/0.0.0.0/9000' || exit 1
      timeout: 5s
      retries: 5
    ports:
      - 9000:9000
      - 9001:9001
    profiles:
      - infra
    restart: on-failure

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    ports:
      - 8000:8000
    profiles:
      - app
    restart: on-failure

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: start --service=worker
    env_file: .env.docker
    profiles:
      - app
    restart: on-failure
