name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  code-check:
    uses: ./.github/workflows/ci-setup.yml
    with:
      COMMAND: bun check:ci

  docker-build:
    uses: ./.github/workflows/docker-build.yml

  test-1:
    uses: ./.github/workflows/ci-setup.yml
    with:
      COMMAND: |
        bun app db:migrate
        bun run test --shard=1/2

  test-2:
    uses: ./.github/workflows/ci-setup.yml
    with:
      COMMAND: |
        bun app db:migrate
        bun run test --shard=2/2
